In [2]:
import numpy as np
import pandas as pd

In [6]:
movies = pd.DataFrame({
    "Movies_ID": [1, 2, 3, 4, 5, 6, 7, 8],
    "Movies_title":["Avengers", "Iron man", "Titanice", "Interseller",
                   "The Dark Knight", "Inception", "Avatar", "Joker"],
    "Genre": ["Action", "Action", "Romance", "Sci-Fi",
             "Action", "Sci-Fi", "Sci-Fi", "Drama"],
    "rating": [4.8, 4.5, 4.2, 4.7, 4.9, 4.6, 4.3, 4.1],
    "votes": [5000, 3500, 4200, 4800, 6000, 5500, 3900, 2800]
})

movies

   Movies_ID     Movies_title    Genre  rating  votes
0          1         Avengers   Action     4.8   5000
1          2         Iron man   Action     4.5   3500
2          3         Titanice  Romance     4.2   4200
3          4      Interseller   Sci-Fi     4.7   4800
4          5  The Dark Knight   Action     4.9   6000
5          6        Inception   Sci-Fi     4.6   5500
6          7           Avatar   Sci-Fi     4.3   3900
7          8            Joker    Drama     4.1   2800

In [7]:
# Explore the data
print("Dataset Shape:", movies.shape)
print("\nDataset Information:-")
movies.info()
print("\nMissing Values:")
print(movies.isnull().sum())
print("\nTop 5 Movies by rating:")
print(movies.sort_values(by="rating", ascending=False).head())

Dataset Shape: (8, 5)

Dataset Information:-
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Movies_ID     8 non-null      int64
 1   Movies_title  8 non-null      str
 2   Genre         8 non-null      str
 3   rating        8 non-null      float64
 4   votes         8 non-null      int64
dtypes: float64(1), int64(2), str(2)
memory usage: 452.0 bytes

Missing Values:
Movies_ID       0
Movies_title    0
Genre           0
rating          0
votes           0
dtype: int64

Top 5 Movies by rating:
   Movies_ID     Movies_title   Genre  rating  votes
4          5  The Dark Knight  Action     4.9   6000
0          1         Avengers  Action     4.8   5000
3          4      Interseller  Sci-Fi     4.7   4800
5          6        Inception  Sci-Fi     4.6   5500
1          2         Iron man  Action     4.5   3500

In [8]:
# build the popularity based recommendar
c = movies["rating"].mean()
m = movies["votes"].quantile(0.50)

movies["Weighted_score"] = (
    (movies["votes"] / (movies["votes"] + m)) * movies["rating"]
    + (m / (movies["votes"] + m)) * c
)

movies[["Movies_title", "rating", "votes", "Weighted_score"]]

      Movies_title  rating  votes  Weighted_score
0         Avengers     4.8   5000        4.663816
1         Iron man     4.5   3500        4.507031
2         Titanice     4.2   4200        4.361638
3      Interseller     4.7   4800        4.609274
4  The Dark Knight     4.9   6000        4.733929
5        Inception     4.6   5500        4.560625
6           Avatar     4.3   3900        4.413839
7            Joker     4.1   2800        4.354281

In [9]:
# Recommend the top 5 movies 
top_movies = movies.sort_values(by="Weighted_score", ascending=False)

print("Top 5 Recommended Movies")
print(top_movies[["Movies_title", "Genre", "Weighted_score"]].head(5).to_string(index=False))

Top 5 Recommended Movies
   Movies_title  Genre  Weighted_score
The Dark Knight Action        4.733929
       Avengers Action        4.663816
    Interseller Sci-Fi        4.609274
      Inception Sci-Fi        4.560625
       Iron man Action        4.507031

In [14]:
# Recommend movies from a specific genre
genre = "Sci-Fi"
genre_recommendations = movies[movies["Genre"] == genre]
genre_recommendations = genre_recommendations.sort_values(by="Weighted_score", ascending=False)

print(f"Recommended {genre} Movies:")
print(genre_recommendations[["Movies_title", "Weighted_score"]].to_string(index=False))

Recommended Sci-Fi Movies:
Movies_title  Weighted_score
 Interseller        4.609274
   Inception        4.560625
      Avatar        4.413839

In [17]:
movies["description"] = [
    "superhero action adventure marvel",
    "superhero action technology marvel",
    "romance drama love ship",
    "science fiction space time travel",
    "superhero action crime batman",
    "science fiction dream mind thriller",
    "science fiction alien adventure",
    "crime drama psychological thriller"
]

movies

,Movies_ID,Movies_title,Genre,rating,votes,Weighted_score,description
0,1,Avengers,Action,4.8,5000,4.663816,superhero action adventure marvel
1,2,Iron man,Action,4.5,3500,4.507031,superhero action technology marvel
2,3,Titanice,Romance,4.2,4200,4.361638,romance drama love ship
3,4,Interseller,Sci-Fi,4.7,4800,4.609274,science fiction space time travel
4,5,The Dark Knight,Action,4.9,6000,4.733929,superhero action crime batman
5,6,Inception,Sci-Fi,4.6,5500,4.560625,science fiction dream mind thriller
6,7,Avatar,Sci-Fi,4.3,3900,4.413839,science fiction alien adventure
7,8,Joker,Drama,4.1,2800,4.354281,crime drama psychological thriller